export const alertsData = [
  {
    id: 1,
    severity: 'Critical',
    severityCount: 1,
    alertName: 'Reconnect Frequency',
    alertRegion: 'South Asia VPN',
    category: 'Network Health',
    metricBreached: 'Reconnects/session > 0.5',
    firstBreached: '2h 10m ago',
    status: 'Open',
    description: 'Reconnect frequency exceeded the acceptable threshold of 0.5 reconnects/session. This may indicate unstable network handoffs or packet fragmentation.',
    chartData: [20, 35, 45, 55, 72],
    chartLabels: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    currentValue: '0.72 reconnects/session',
    threshold: '0.5',
    affectedSessions: '7.4%',
    mostImpactedRegion: 'South Asia',
    detailCategory: 'Network Health',
    link: '/connection-stability',
  },
  {
    id: 2,
    severity: 'Warning',
    severityCount: 4,
    alertName: 'MTU Errors Elevated',
    alertRegion: 'UDP - APAC',
    category: 'Protocol & Traffic',
    metricBreached: 'MTU < 1400 bytes',
    firstBreached: '5h ago',
    status: 'Acknowledged',
    description: 'MTU error rate has exceeded threshold. Packet fragmentation may be impacting performance.',
    chartData: [30, 38, 42, 48, 55],
    chartLabels: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    currentValue: '1350 bytes',
    threshold: '1400 bytes',
    affectedSessions: '3.2%',
    mostImpactedRegion: 'APAC',
    detailCategory: 'Protocol & Traffic',
    link: '/protocol-overview',
  },
  {
    id: 3,
    severity: 'Critical',
    severityCount: 1,
    alertName: 'Medion Latency Breach',
    alertRegion: 'EU-West',
    category: 'Performance & Quality',
    metricBreached: 'Latency > 150ms',
    firstBreached: '1m ago',
    status: 'Open',
    description: 'Median latency has exceeded 150ms threshold in EU-West region.',
    chartData: [80, 100, 120, 140, 165],
    chartLabels: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    currentValue: '165ms',
    threshold: '150ms',
    affectedSessions: '12.1%',
    mostImpactedRegion: 'EU-West',
    detailCategory: 'Performance & Quality',
    link: '/performance-quality',
  },
  {
    id: 4,
    severity: 'Informational',
    severityCount: 1,
    alertName: 'High Egress per Session',
    alertRegion: 'Grotate',
    category: 'Global',
    metricBreached: 'Egress/session > 230MB',
    firstBreached: '1 day ago',
    status: 'Open',
    description: 'Egress volume per session has exceeded 230MB. Monitor for capacity planning.',
    chartData: [180, 195, 210, 225, 245],
    chartLabels: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    currentValue: '245MB',
    threshold: '230MB',
    affectedSessions: '2.1%',
    mostImpactedRegion: 'US-East',
    detailCategory: 'Global',
    link: '/network-overview',
  },
  {
    id: 5,
    severity: 'Warning',
    severityCount: 4,
    alertName: 'Excessive Drop Rate',
    alertRegion: 'US East',
    category: 'Protocol & Traffic',
    metricBreached: 'Drop packets > 2.0%',
    firstBreached: '3 days ago',
    status: 'Open',
    description: 'Packet drop rate has exceeded 2% threshold in US East.',
    chartData: [1.2, 1.5, 1.8, 2.1, 2.4],
    chartLabels: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    currentValue: '2.4%',
    threshold: '2.0%',
    affectedSessions: '5.8%',
    mostImpactedRegion: 'US-East',
    detailCategory: 'Protocol & Traffic',
    link: '/reliability-failure',
  },
  {
    id: 6,
    severity: 'Warning',
    severityCount: 4,
    alertName: 'Idle Tunnel Accumulation',
    alertRegion: 'EU-West - A CDN',
    category: 'Capacity & Scaling',
    metricBreached: 'Idle tunnel > 50%',
    firstBreached: '5 days ago',
    status: 'Resolved',
    description: 'Idle tunnel percentage has been resolved. Capacity is now within normal range.',
    chartData: [55, 52, 48, 45, 42],
    chartLabels: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    currentValue: '42%',
    threshold: '50%',
    affectedSessions: '0%',
    mostImpactedRegion: 'EU-West',
    detailCategory: 'Capacity & Scaling',
    link: '/current-capacity',
  },
  {
    id: 7,
    severity: 'Warning',
    severityCount: 2,
    alertName: 'Session Timeout Spike',
    alertRegion: 'North America',
    category: 'Session Behavior',
    metricBreached: 'Timeout/session > 3',
    firstBreached: '6h ago',
    status: 'Open',
    description: 'Session timeout rate has increased above threshold.',
    chartData: [1.5, 2, 2.2, 2.5, 3.2],
    chartLabels: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    currentValue: '3.2',
    threshold: '3',
    affectedSessions: '4.1%',
    mostImpactedRegion: 'North America',
    detailCategory: 'Session Behavior',
    link: '/session-behavior',
  },
  {
    id: 8,
    severity: 'Critical',
    severityCount: 1,
    alertName: 'High Packet Fragmentation',
    alertRegion: 'South Asia UDP',
    category: 'Network Health',
    metricBreached: 'MTU < 1280 bytes',
    firstBreached: '3 hours ago',
    status: 'Open',
    description: 'Packet fragmentation exceeds acceptable levels. MTU below 1280 bytes threshold.',
    chartData: [1350, 1320, 1300, 1285, 1250],
    chartLabels: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
    currentValue: '1250 bytes',
    threshold: '1280 bytes',
    affectedSessions: '8.3%',
    mostImpactedRegion: 'South Asia',
    detailCategory: 'Network Health',
    link: '/connection-stability',
  },
]

export const mostAffectedArea = {
  label: 'Network and Protocol Health',
  percentage: '9.3%',
}
