// Data structure for each VPN
export const vpnData = {
  Portfolio: {
    kpiData: [
      {
        title: 'Concurrent Users',
        value: '89,935',
        trend: 10.2,
        change: '+1.01%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Active Tunnels',
        value: '23,283.5',
        trend: 3.1,
        change: '+0.49%',
        period: 'this week',
        direction: 'up',
        iconType: 'filter',
        iconColor: 'red',
      },
      {
        title: 'DAU',
        value: '165,980',
        trend: 2.56,
        change: '-0.91%',
        period: 'this week',
        direction: 'down',
        iconType: 'clock',
        iconColor: 'gray',
      },
      {
        title: 'MAU',
        value: '3.2 m',
        trend: 7.2,
        change: '+1.51%',
        period: 'this week',
        direction: 'up',
        iconType: 'calendar',
        iconColor: 'purple',
      },
      {
        title: 'Total Registered Users',
        value: '89,935',
        trend: 10.2,
        change: '+1.01%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Total Installs',
        value: '23,283.5',
        trend: 3.1,
        change: '+0.49%',
        period: 'this week',
        direction: 'up',
        iconType: 'backpack',
        iconColor: 'red',
      },
      {
        title: 'Cost Per Active Users',
        value: '3.2 m',
        trend: 7.2,
        change: '+1.51%',
        period: 'this week',
        direction: 'up',
        iconType: 'dollar',
        iconColor: 'green',
        hasGradient: true,
      },
    ],
    alerts: [
      {
        title: 'VPN-5: High Drop Rate',
        description: 'Tunnel drop rate at 3.8% (threshold: 2%)',
        level: 'High Alert',
        link: 'View VPN-5',
      },
      {
        title: 'Asia Pacific: Degraded',
        description: 'Latency spike detected (52ms avg)',
        level: 'Medium Level Alert',
        link: 'View Region',
      },
      {
        title: 'VPN-5: High Drop Rate',
        description: 'Tunnel drop rate at 3.8% (threshold: 2%)',
        level: 'High Alert',
        link: 'View VPN-5',
      },
      {
        title: 'Asia Pacific: Degraded',
        description: 'Latency spike detected (52ms avg)',
        level: 'Medium Level Alert',
        link: 'View Region',
      },
    ],
    categoryCards: [
      {
        title: 'Network Health and Stability',
        status: 'green',
        statusText: 'Green',
        percentage: '21%',
        description: 'Cost efficiency within threshold',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Capacity and Scaling',
        status: 'green',
        statusText: 'Green',
        percentage: '18%',
        description: 'Scaling efficiency optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Cost and Unit Economics',
        status: 'green',
        statusText: 'Green',
        percentage: '15%',
        description: 'Unit costs within target range',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Protocol and Traffic Mix',
        status: 'green',
        statusText: 'Green',
        percentage: '12%',
        description: 'Traffic distribution balanced',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Growth and Product Performance',
        status: 'red',
        statusText: 'Red',
        percentage: '45%',
        description: 'Performance metrics below threshold',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Compliance and Governance',
        status: 'green',
        statusText: 'Green',
        percentage: '8%',
        description: 'Compliance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
    ],
    healthStatus: {
      status: 'Critical',
      gaugePercent: 0.68,
      activeIssues: 17,
    },
  },
  'Steer Lucid': {
    kpiData: [
      {
        title: 'Average Current Utilization',
        value: '125,430',
        trend: 8.5,
        change: '+0.85%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Active Tunnels',
        value: '31,542.3',
        trend: 4.2,
        change: '+0.62%',
        period: 'this week',
        direction: 'up',
        iconType: 'filter',
        iconColor: 'red',
      },
      {
        title: 'DAU (Daily Active Users)',
        value: '198,650',
        trend: 3.8,
        change: '-1.2%',
        period: 'this week',
        direction: 'down',
        iconType: 'clock',
        iconColor: 'gray',
      },
      {
        title: 'MAU (Monthly Active Users)',
        value: '4.5 m',
        trend: 9.1,
        change: '+2.1%',
        period: 'this week',
        direction: 'up',
        iconType: 'calendar',
        iconColor: 'purple',
      },
      {
        title: 'Total Registered Users',
        value: '125,430',
        trend: 8.5,
        change: '+0.85%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Total Installs',
        value: '31,542.3',
        trend: 4.2,
        change: '+0.62%',
        period: 'this week',
        direction: 'up',
        iconType: 'backpack',
        iconColor: 'red',
      },
      {
        title: 'Cost Per Active Users',
        value: '4.5 m',
        trend: 9.1,
        change: '+2.1%',
        period: 'this week',
        direction: 'up',
        iconType: 'dollar',
        iconColor: 'green',
        hasGradient: true,
      },
    ],
    alerts: [
      {
        title: 'Steer Lucid-3: Connection Issues',
        description: 'Multiple connection failures detected (4.2% failure rate)',
        level: 'High Alert',
        link: 'View Steer Lucid-3',
      },
      {
        title: 'North America: High Latency',
        description: 'Average latency increased to 65ms',
        level: 'Medium Level Alert',
        link: 'View Region',
      },
      {
        title: 'Steer Lucid-3: Connection Issues',
        description: 'Multiple connection failures detected (4.2% failure rate)',
        level: 'High Alert',
        link: 'View Steer Lucid-3',
      },
    ],
    categoryCards: [
      {
        title: 'Network Health and Stability',
        status: 'red',
        statusText: 'Red',
        percentage: '35%',
        description: 'Network stability below threshold',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Capacity and Scaling',
        status: 'green',
        statusText: 'Green',
        percentage: '22%',
        description: 'Scaling efficiency optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Cost and Unit Economics',
        status: 'green',
        statusText: 'Green',
        percentage: '18%',
        description: 'Unit costs within target range',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Protocol and Traffic Mix',
        status: 'green',
        statusText: 'Green',
        percentage: '15%',
        description: 'Traffic distribution balanced',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Growth and Product Performance',
        status: 'green',
        statusText: 'Green',
        percentage: '28%',
        description: 'Performance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Compliance and Governance',
        status: 'green',
        statusText: 'Green',
        percentage: '12%',
        description: 'Compliance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
    ],
    healthStatus: {
      status: 'Strained',
      gaugePercent: 0.55,
      activeIssues: 12,
    },
  },
  Crest: {
    kpiData: [
      {
        title: 'Average Current Utilization',
        value: '67,892',
        trend: 5.8,
        change: '+0.45%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Active Tunnels',
        value: '18,456.7',
        trend: 2.3,
        change: '+0.32%',
        period: 'this week',
        direction: 'up',
        iconType: 'filter',
        iconColor: 'red',
      },
      {
        title: 'DAU (Daily Active Users)',
        value: '142,380',
        trend: 1.9,
        change: '-0.65%',
        period: 'this week',
        direction: 'down',
        iconType: 'clock',
        iconColor: 'gray',
      },
      {
        title: 'MAU (Monthly Active Users)',
        value: '2.8 m',
        trend: 4.5,
        change: '+0.95%',
        period: 'this week',
        direction: 'up',
        iconType: 'calendar',
        iconColor: 'purple',
      },
      {
        title: 'Total Registered Users',
        value: '67,892',
        trend: 5.8,
        change: '+0.45%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Total Installs',
        value: '18,456.7',
        trend: 2.3,
        change: '+0.32%',
        period: 'this week',
        direction: 'up',
        iconType: 'backpack',
        iconColor: 'red',
      },
      {
        title: 'Cost Per Active Users',
        value: '2.8 m',
        trend: 4.5,
        change: '+0.95%',
        period: 'this week',
        direction: 'up',
        iconType: 'dollar',
        iconColor: 'green',
        hasGradient: true,
      },
    ],
    alerts: [
      {
        title: 'Crest-2: Bandwidth Limit',
        description: 'Bandwidth usage at 92% capacity',
        level: 'Medium Level Alert',
        link: 'View Crest-2',
      },
      {
        title: 'Europe: Service Degradation',
        description: 'Service availability dropped to 98.5%',
        level: 'Medium Level Alert',
        link: 'View Region',
      },
      {
        title: 'Crest-2: Bandwidth Limit',
        description: 'Bandwidth usage at 92% capacity',
        level: 'Medium Level Alert',
        link: 'View Crest-2',
      },
    ],
    categoryCards: [
      {
        title: 'Network Health and Stability',
        status: 'green',
        statusText: 'Green',
        percentage: '28%',
        description: 'Network stability optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Capacity and Scaling',
        status: 'green',
        statusText: 'Green',
        percentage: '25%',
        description: 'Scaling efficiency optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Cost and Unit Economics',
        status: 'green',
        statusText: 'Green',
        percentage: '20%',
        description: 'Unit costs within target range',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Protocol and Traffic Mix',
        status: 'green',
        statusText: 'Green',
        percentage: '18%',
        description: 'Traffic distribution balanced',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Growth and Product Performance',
        status: 'green',
        statusText: 'Green',
        percentage: '32%',
        description: 'Performance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Compliance and Governance',
        status: 'green',
        statusText: 'Green',
        percentage: '15%',
        description: 'Compliance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
    ],
    healthStatus: {
      status: 'Healthy',
      gaugePercent: 0.42,
      activeIssues: 8,
    },
  },
  Slick: {
    kpiData: [
      {
        title: 'Average Current Utilization',
        value: '95,234',
        trend: 7.4,
        change: '+0.68%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Active Tunnels',
        value: '26,789.2',
        trend: 3.6,
        change: '+0.52%',
        period: 'this week',
        direction: 'up',
        iconType: 'filter',
        iconColor: 'red',
      },
      {
        title: 'DAU (Daily Active Users)',
        value: '178,920',
        trend: 2.9,
        change: '-0.78%',
        period: 'this week',
        direction: 'down',
        iconType: 'clock',
        iconColor: 'gray',
      },
      {
        title: 'MAU (Monthly Active Users)',
        value: '3.6 m',
        trend: 6.8,
        change: '+1.35%',
        period: 'this week',
        direction: 'up',
        iconType: 'calendar',
        iconColor: 'purple',
      },
      {
        title: 'Total Registered Users',
        value: '95,234',
        trend: 7.4,
        change: '+0.68%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Total Installs',
        value: '26,789.2',
        trend: 3.6,
        change: '+0.52%',
        period: 'this week',
        direction: 'up',
        iconType: 'backpack',
        iconColor: 'red',
      },
      {
        title: 'Cost Per Active Users',
        value: '3.6 m',
        trend: 6.8,
        change: '+1.35%',
        period: 'this week',
        direction: 'up',
        iconType: 'dollar',
        iconColor: 'green',
        hasGradient: true,
      },
    ],
    alerts: [
      {
        title: 'Slick-4: Performance Issue',
        description: 'Response time increased to 120ms',
        level: 'High Alert',
        link: 'View Slick-4',
      },
      {
        title: 'South America: Connectivity Problems',
        description: 'Connection success rate at 96%',
        level: 'Medium Level Alert',
        link: 'View Region',
      },
      {
        title: 'Slick-4: Performance Issue',
        description: 'Response time increased to 120ms',
        level: 'High Alert',
        link: 'View Slick-4',
      },
      {
        title: 'South America: Connectivity Problems',
        description: 'Connection success rate at 96%',
        level: 'Medium Level Alert',
        link: 'View Region',
      },
    ],
    categoryCards: [
      {
        title: 'Network Health and Stability',
        status: 'green',
        statusText: 'Green',
        percentage: '24%',
        description: 'Network stability good',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Capacity and Scaling',
        status: 'green',
        statusText: 'Green',
        percentage: '20%',
        description: 'Scaling efficiency optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Cost and Unit Economics',
        status: 'green',
        statusText: 'Green',
        percentage: '16%',
        description: 'Unit costs within target range',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Protocol and Traffic Mix',
        status: 'green',
        statusText: 'Green',
        percentage: '14%',
        description: 'Traffic distribution balanced',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Growth and Product Performance',
        status: 'red',
        statusText: 'Red',
        percentage: '38%',
        description: 'Performance metrics below threshold',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Compliance and Governance',
        status: 'green',
        statusText: 'Green',
        percentage: '10%',
        description: 'Compliance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
    ],
    healthStatus: {
      status: 'At Risk',
      gaugePercent: 0.58,
      activeIssues: 14,
    },
  },
  Fortivo: {
    kpiData: [
      {
        title: 'Average Current Utilization',
        value: '112,567',
        trend: 9.3,
        change: '+0.92%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Active Tunnels',
        value: '29,345.8',
        trend: 4.8,
        change: '+0.71%',
        period: 'this week',
        direction: 'up',
        iconType: 'filter',
        iconColor: 'red',
      },
      {
        title: 'DAU (Daily Active Users)',
        value: '192,450',
        trend: 4.2,
        change: '-1.05%',
        period: 'this week',
        direction: 'down',
        iconType: 'clock',
        iconColor: 'gray',
      },
      {
        title: 'MAU (Monthly Active Users)',
        value: '4.2 m',
        trend: 8.7,
        change: '+1.88%',
        period: 'this week',
        direction: 'up',
        iconType: 'calendar',
        iconColor: 'purple',
      },
      {
        title: 'Total Registered Users',
        value: '112,567',
        trend: 9.3,
        change: '+0.92%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Total Installs',
        value: '29,345.8',
        trend: 4.8,
        change: '+0.71%',
        period: 'this week',
        direction: 'up',
        iconType: 'backpack',
        iconColor: 'red',
      },
      {
        title: 'Cost Per Active Users',
        value: '4.2 m',
        trend: 8.7,
        change: '+1.88%',
        period: 'this week',
        direction: 'up',
        iconType: 'dollar',
        iconColor: 'green',
        hasGradient: true,
      },
    ],
    alerts: [
      {
        title: 'Fortivo-1: Security Alert',
        description: 'Unusual traffic pattern detected',
        level: 'High Alert',
        link: 'View Fortivo-1',
      },
      {
        title: 'Middle East: Service Outage',
        description: 'Partial service interruption (5% users affected)',
        level: 'High Alert',
        link: 'View Region',
      },
      {
        title: 'Fortivo-1: Security Alert',
        description: 'Unusual traffic pattern detected',
        level: 'High Alert',
        link: 'View Fortivo-1',
      },
      {
        title: 'Middle East: Service Outage',
        description: 'Partial service interruption (5% users affected)',
        level: 'High Alert',
        link: 'View Region',
      },
    ],
    categoryCards: [
      {
        title: 'Network Health and Stability',
        status: 'red',
        statusText: 'Red',
        percentage: '42%',
        description: 'Network stability critical',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Capacity and Scaling',
        status: 'green',
        statusText: 'Green',
        percentage: '19%',
        description: 'Scaling efficiency optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Cost and Unit Economics',
        status: 'green',
        statusText: 'Green',
        percentage: '17%',
        description: 'Unit costs within target range',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Protocol and Traffic Mix',
        status: 'green',
        statusText: 'Green',
        percentage: '13%',
        description: 'Traffic distribution balanced',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Growth and Product Performance',
        status: 'green',
        statusText: 'Green',
        percentage: '31%',
        description: 'Performance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Compliance and Governance',
        status: 'green',
        statusText: 'Green',
        percentage: '11%',
        description: 'Compliance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
    ],
    healthStatus: {
      status: 'Critical',
      gaugePercent: 0.72,
      activeIssues: 19,
    },
  },
  Qucik: {
    kpiData: [
      {
        title: 'Average Current Utilization',
        value: '78,345',
        trend: 6.2,
        change: '+0.54%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Active Tunnels',
        value: '21,567.4',
        trend: 2.8,
        change: '+0.38%',
        period: 'this week',
        direction: 'up',
        iconType: 'filter',
        iconColor: 'red',
      },
      {
        title: 'DAU (Daily Active Users)',
        value: '155,780',
        trend: 2.1,
        change: '-0.52%',
        period: 'this week',
        direction: 'down',
        iconType: 'clock',
        iconColor: 'gray',
      },
      {
        title: 'MAU (Monthly Active Users)',
        value: '3.0 m',
        trend: 5.4,
        change: '+1.12%',
        period: 'this week',
        direction: 'up',
        iconType: 'calendar',
        iconColor: 'purple',
      },
      {
        title: 'Total Registered Users',
        value: '78,345',
        trend: 6.2,
        change: '+0.54%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Total Installs',
        value: '21,567.4',
        trend: 2.8,
        change: '+0.38%',
        period: 'this week',
        direction: 'up',
        iconType: 'backpack',
        iconColor: 'red',
      },
      {
        title: 'Cost Per Active Users',
        value: '3.0 m',
        trend: 5.4,
        change: '+1.12%',
        period: 'this week',
        direction: 'up',
        iconType: 'dollar',
        iconColor: 'green',
        hasGradient: true,
      },
    ],
    alerts: [
      {
        title: 'Qucik-6: Bandwidth Overload',
        description: 'Bandwidth usage exceeded 95% threshold',
        level: 'High Alert',
        link: 'View Qucik-6',
      },
      {
        title: 'Africa: Network Congestion',
        description: 'High network congestion detected',
        level: 'Medium Level Alert',
        link: 'View Region',
      },
      {
        title: 'Qucik-6: Bandwidth Overload',
        description: 'Bandwidth usage exceeded 95% threshold',
        level: 'High Alert',
        link: 'View Qucik-6',
      },
    ],
    categoryCards: [
      {
        title: 'Network Health and Stability',
        status: 'green',
        statusText: 'Green',
        percentage: '26%',
        description: 'Network stability good',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Capacity and Scaling',
        status: 'green',
        statusText: 'Green',
        percentage: '23%',
        description: 'Scaling efficiency optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Cost and Unit Economics',
        status: 'green',
        statusText: 'Green',
        percentage: '19%',
        description: 'Unit costs within target range',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Protocol and Traffic Mix',
        status: 'green',
        statusText: 'Green',
        percentage: '16%',
        description: 'Traffic distribution balanced',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Growth and Product Performance',
        status: 'green',
        statusText: 'Green',
        percentage: '29%',
        description: 'Performance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Compliance and Governance',
        status: 'green',
        statusText: 'Green',
        percentage: '13%',
        description: 'Compliance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
    ],
    healthStatus: {
      status: 'Strained',
      gaugePercent: 0.49,
      activeIssues: 10,
    },
  },
  Nexipher: {
    kpiData: [
      {
        title: 'Average Current Utilization',
        value: '103,890',
        trend: 8.9,
        change: '+0.87%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Active Tunnels',
        value: '27,234.6',
        trend: 4.5,
        change: '+0.66%',
        period: 'this week',
        direction: 'up',
        iconType: 'filter',
        iconColor: 'red',
      },
      {
        title: 'DAU (Daily Active Users)',
        value: '185,670',
        trend: 3.7,
        change: '-0.95%',
        period: 'this week',
        direction: 'down',
        iconType: 'clock',
        iconColor: 'gray',
      },
      {
        title: 'MAU (Monthly Active Users)',
        value: '3.9 m',
        trend: 7.9,
        change: '+1.68%',
        period: 'this week',
        direction: 'up',
        iconType: 'calendar',
        iconColor: 'purple',
      },
      {
        title: 'Total Registered Users',
        value: '103,890',
        trend: 8.9,
        change: '+0.87%',
        period: 'this week',
        direction: 'up',
        iconType: 'users',
        iconColor: 'gray',
      },
      {
        title: 'Total Installs',
        value: '27,234.6',
        trend: 4.5,
        change: '+0.66%',
        period: 'this week',
        direction: 'up',
        iconType: 'backpack',
        iconColor: 'red',
      },
      {
        title: 'Cost Per Active Users',
        value: '3.9 m',
        trend: 7.9,
        change: '+1.68%',
        period: 'this week',
        direction: 'up',
        iconType: 'dollar',
        iconColor: 'green',
        hasGradient: true,
      },
    ],
    alerts: [
      {
        title: 'Nexipher-7: Memory Leak',
        description: 'Memory usage continuously increasing',
        level: 'High Alert',
        link: 'View Nexipher-7',
      },
      {
        title: 'Asia: Database Connection Issues',
        description: 'Database connection pool exhausted',
        level: 'High Alert',
        link: 'View Region',
      },
      {
        title: 'Nexipher-7: Memory Leak',
        description: 'Memory usage continuously increasing',
        level: 'High Alert',
        link: 'View Nexipher-7',
      },
      {
        title: 'Asia: Database Connection Issues',
        description: 'Database connection pool exhausted',
        level: 'High Alert',
        link: 'View Region',
      },
    ],
    categoryCards: [
      {
        title: 'Network Health and Stability',
        status: 'red',
        statusText: 'Red',
        percentage: '39%',
        description: 'Network stability critical',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Capacity and Scaling',
        status: 'green',
        statusText: 'Green',
        percentage: '21%',
        description: 'Scaling efficiency optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Cost and Unit Economics',
        status: 'green',
        statusText: 'Green',
        percentage: '16%',
        description: 'Unit costs within target range',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Protocol and Traffic Mix',
        status: 'green',
        statusText: 'Green',
        percentage: '14%',
        description: 'Traffic distribution balanced',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Growth and Product Performance',
        status: 'red',
        statusText: 'Red',
        percentage: '41%',
        description: 'Performance metrics below threshold',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
      {
        title: 'Compliance and Governance',
        status: 'green',
        statusText: 'Green',
        percentage: '10%',
        description: 'Compliance metrics optimal',
        chartData: [85, 75, 45, 55, 15, 35, 20, 50, 60, 70],
      },
    ],
    healthStatus: {
      status: 'Critical',
      gaugePercent: 0.65,
      activeIssues: 16,
    },
  },
}

